const data = {
  status: "success",
  items: [
    {
        id: 1,
        name: "Spider-Man",
        developers: "Insomniac Games",
        image: "https://image.api.playstation.com/vulcan/ap/rnd/202011/0402/AcjaXqwZzggGiKLFdEfHMp0H.png",
        banner: "https://scontent.fbog9-1.fna.fbcdn.net/v/t39.30808-6/241901344_4394326320635036_8552673016699605314_n.jpg?_nc_cat=102&ccb=1-5&_nc_sid=0debeb&_nc_ohc=HLOIMhhmhowAX_vc7am&_nc_ht=scontent.fbog9-1.fna&oh=58a32bef6da8aee9f25a4fac8bf2c362&oe=61441F96",
        description: "Marvel's Spider-Man es un videojuego de acción y aventura basado en el popular superhéroe hómonimo de la editorial Marvel Comics.​ Fue desarrollado por Insomniac Games y publicado por Sony Interactive Entertainment en exclusiva para la consola PlayStation 4.",
        platform: "PlayStation",
        price: 136000,
        video: "https://www.youtube.com/watch?v=q4GdJVvdxss",
        category: "Accion y Aventura",
        cantidad: 1,
        __v: 0
    },
    {
        id: 2,
        name: "The Last of Us Part II",
        developers: "Naughty Dog",
        image: "https://pbs.twimg.com/media/ErJT1seUcAApaJx.jpg",
        banner: "https://scontent.fbog9-1.fna.fbcdn.net/v/t39.30808-6/241978720_4394335510634117_7329695296403774294_n.jpg?_nc_cat=108&ccb=1-5&_nc_sid=0debeb&_nc_ohc=cJ4Eq5WAnIQAX_8Koln&_nc_ht=scontent.fbog9-1.fna&oh=2c6fcfb81a1d9a933cdf09acbae1cd4a&oe=61444926",
        description: "The Last of Us Part II es un juego de acción y aventuras de 2020 desarrollado por Naughty Dog y publicado por Sony Interactive Entertainment para PlayStation 4.1​ Ambientado cinco años después de The Last of Us (2013), el juego se centra en dos personajes jugables en un Estados Unidos post-apocalíptico cuyas vidas se entrelazan: Ellie, que busca venganza después de sufrir una tragedia, y Abby, una soldado que se ve envuelta en un conflicto entre su milicia y un culto religioso.",
        platform: "PlayStation",
        price: 110000,
        video: "https://www.youtube.com/watch?v=VSLSvEjDm5s&t=4s",
        category: "Accion y Aventura",
        cantidad: 1,
        __v: 0
    },
    {
        id: 3,
        name: "God of War",
        developers: "Santa Monica Studio",
        image: "https://as01.epimg.net/meristation/imagenes/2020/09/17/game_cover/479791341600340811.jpg",
        banner: "https://scontent.fbog9-1.fna.fbcdn.net/v/t39.30808-6/241788291_4394382803962721_3030555745143859774_n.jpg?_nc_cat=111&ccb=1-5&_nc_sid=0debeb&_nc_ohc=2oXMbtEsBSwAX_M4nkP&tn=GFcIcWpL9Ezc8Wu8&_nc_ht=scontent.fbog9-1.fna&oh=e3dc23fa87fc778efea1d721de291515&oe=614314AC",
        description: "God of War (en español Dios de la Guerra) es una serie de videojuegos en 3ª. persona creada por SCE Santa Monica Studio y distribuida por Sony Computer Entertainment. Se basa en las aventuras de un semidiós espartano, Kratos, quien se enfrenta a diversos personajes de la mitología griega y nórdica, tanto héroes (Heracles, Teseo, Perseo, etc.); especies mitológicas (gorgonas, arpías, o minotauros); dioses griegos (Ares, Poseidón, Zeus, entre otros), titanes (como Cronos) y dioses primordiales (como Gaia). Aunque el guerrero espartano acostumbra enemistad con la mayoría de los dioses, recibe ayuda de muchos de ellos en algún momento de cada entrega, en especial de Atenea.",
        platform: "PlayStation",
        price: 90000,
        video: "https://www.youtube.com/watch?v=AN3jEjjcZ-k",
        category: "Accion y Aventura",
        cantidad: 1,
        __v: 0
    },
    {
        id: 4,
        name: "Ghost of Tsushima",
        developers: "Sucker Punch",
        image: "https://i.pinimg.com/736x/e3/98/37/e39837367663ed5a77887210624cfd95.jpg",
        banner: "https://scontent.fbog9-1.fna.fbcdn.net/v/t39.30808-6/241694417_4384363208298014_6039015418520193638_n.jpg?_nc_cat=110&ccb=1-5&_nc_sid=0debeb&_nc_ohc=9LQBRJQ0Vo8AX_332aD&tn=GFcIcWpL9Ezc8Wu8&_nc_ht=scontent.fbog9-1.fna&oh=a6950e41795d58249680d4ac747444c2&oe=61409404",
        description: "Ghost of Tsushima es un videojuego de acción-aventura desarrollado por Sucker Punch Productions y publicado por Sony Interactive Entertainment para PlayStation 4 y PlayStation 5. Con un mundo abierto para que los jugadores exploren, el juego gira en torno al último samurái en la isla de Tsushima durante la primera invasión mongola de Japón. El lanzamiento del juego se produjo el 17 de julio de 2020",
        platform: "PlayStation",
        price: 160000,
        video: "https://www.youtube.com/watch?v=MUz539AeC5Y",
        category: "Accion y Aventura",
        cantidad: 1,
        __v: 0
    },
    {
        id: 5,
        name: "Uncharted 4",
        developers: "Naughty Dog",
        image: "https://b.allegroimg.com/s1024/0c0dc9/4c06c7c846e7b435a1a9d87b500b",
        banner: "https://s1.1zoom.me/b5050/982/Uncharted_4_A_Thief’s_End_Men_Pistols_534881_1366x768.jpg",
        description: "Uncharted 4: El desenlace del ladrón, es un videojuego de acción-aventura en tercera persona, lanzado el 10 de mayo de 2016, distribuido por Sony Computer Entertainment y desarrollado por Naughty Dog exclusivamente para PlayStation 4.​",
        platform: "PlayStation",
        price: 60000,
        video: "https://www.youtube.com/watch?v=hh5HV4iic1Y",
        category: "Accion y Aventura",
        cantidad: 1,
        __v: 0
    },
    {
        id: 6,
        name: "Days Gone",
        developers: "SIE Bend Studio",
        image: "https://i.3djuegos.com/juegos/13416/days_gone_/fotos/ficha/days_gone_-5370492.jpg",
        banner: "https://i.blogs.es/2bd884/days-gone/1366_2000.jpeg",
        description: "Days Gone es un videojuego de acción-aventura y horror de supervivencia, desarrollado por el estudio SIE Bend Studio y publicado por Sony Interactive Entertainment para PlayStation 4 y Microsoft Windows. Fue lanzado en PlayStation 4 el 26 de abril del año 2019 y el 18 de mayo de 2021 para Microsoft Windows",
        platform: "PlayStation",
        price: 80000,
        video: "https://www.youtube.com/watch?v=FKtaOY9lMvM",
        category: "Horror de supervivencia",
        cantidad: 1,
        __v: 0
    },
    {
        id: 7,
        name: "Horizon Zero Dawn",
        developers: "Insomniac Games",
        image: "https://cdn1.epicgames.com/3328b08ac1c14540aa265a1a85c07839/offer/hzd_tall-1200x1600-d4b1057afd47f9256d8da71f2f187be4.jpg",
        banner: "https://scontent.fbog9-1.fna.fbcdn.net/v/t39.30808-6/241976996_4394341970633471_8133173192666142917_n.jpg?_nc_cat=110&ccb=1-5&_nc_sid=0debeb&_nc_ohc=nZZ15pGJyxIAX_rp35n&_nc_ht=scontent.fbog9-1.fna&oh=680298182199918dfc0ec92f7fbfcffd&oe=6143CAAB",
        description: "Horizon Zero Dawn es un videojuego de acción, aventura y de mundo abierto desarrollado por Guerrilla Games y distribuido por Sony Interactive Entertainment para PlayStation 4. Es la primera propiedad intelectual de Guerrilla Games desde la serie Killzone en 2004 y se anunció por primera vez en el E3 2015.​",
        platform: "PlayStation",
        price: 70000,
        video: "https://www.youtube.com/watch?v=_BvZvkT5QHw",
        category: "Accion y Aventura",
        cantidad: 1,
        __v: 0
    },
    {
        id: 8,
        name: "Demon's Souls",
        developers: "FromSoftware",
        image: "https://as01.epimg.net/meristation/imagenes/2020/09/17/game_cover/831932761600337753.jpg",
        banner: "https://www.cinepremiere.com.mx/wp-content/uploads/2020/11/demon-s-souls.jpg",
        description: "Demon's Souls es un videojuego de rol de acción en tercera persona desarrollado por la compañía de videojuegos japonesa FromSoftware exclusivamente para la consola PlayStation 3 bajo la supervisión de Japan Studio.",
        platform: "PlayStation 5",
        price: 280000,
        video: "https://www.youtube.com/watch?v=9AyX2QqPKaY",
        category: "Rol de Accion",
        cantidad: 1,
        __v: 0
    },
    {
        id: 9,
        name: "Gran Turismo Sport",
        developers: "Insomniac Games",
        image: "https://metarankings.ru/wp-content/uploads/Gran-Turismo-Sport-b0xart-cover.jpg",
        banner: "https://images6.alphacoders.com/104/thumb-1920-1041796.jpg",
        description: "Gran Turismo Sport es un videojuego de carreras desarrollado por Polyphony Digital y publicado por Sony Interactive Entertainment para la consola de videojuegos PlayStation 4",
        platform: "PlayStation",
        price: 75000,
        video: "https://www.youtube.com/watch?v=moDdHXpxWrw",
        category: "Carreras",
        cantidad: 1,
        __v: 0
    },
    {
        id: 10,
        name: "Bloodborne",
        developers: "Insomniac Games",
        image: "https://cdn.alfabetajuega.com/wp-content/uploads/2019/06/bloodborne-1.jpg",
        banner: "https://images3.alphacoders.com/641/thumb-1920-641193.jpg",
        description: "Bloodborne es un videojuego de rol de acción dirigido por Hidetaka Miyazaki, desarrollado por From Software y JapanStudio distribuido por Sony Computer Entertainment para la plataforma de PlayStation 4",
        platform: "PlayStation",
        price: 85000,
        video: "https://www.youtube.com/watch?v=G203e1HhixY",
        category: "Rol de Accion",
        cantidad: 1,
        __v: 0
    },
    {
        id: 11,
        name: "Sekiro: Shadows Die Twice",
        developers: "FromSoftware",
        image: "https://img.ppcn.net/uploadfile/2021/0219/20210219015848501.jpg",
        banner: "https://images.alphacoders.com/942/thumb-1920-942234.jpg",
        description: "Sekiro: Shadows Die Twice es un videojuego de acción y aventura desarrollado por From Software y distribuido por Activision.​ El juego fue lanzado el 22 de marzo de 2019 en las plataformas PlayStation 4, Xbox One y Microsoft Windows.​",
        platform: "PlayStation",
        price: 100000,
        video: "https://www.youtube.com/watch?v=rXMX4YJ7Lks",
        category: "Rol de Accion",
        cantidad: 1,
        __v: 0
    },
    {
        id: 12,
        name: "Red Dead Redemption 2",
        developers: "Rockstar Games",
        image: "https://assets.mycast.io/posters/red-dead-redemption-2-fan-casting-poster-4262-medium.jpg?1563891849",
        banner: "https://blogs-images.forbes.com/erikkain/files/2018/08/Screenshot-193.png",
        description: "Red Dead Redemption 2, estilizado Red Dead Redemption II, es un videojuego de acción-aventura western, en un mundo abierto y en perspectiva de primera y tercera persona, ​ con componentes para un jugador y multijugador.​ Fue desarrollado por Rockstar Games.​",
        platform: "PlayStation",
        price: 95000,
        video: "https://www.youtube.com/watch?v=gmA6MrX81z4",
        category: "Accion y Aventura",
        cantidad: 1,
        __v: 0
    },
    {
        id: 13,
        name: "Fifa 21",
        developers: "Electronic Arts",
        image: "https://thesamstore.com/wp-content/uploads/2020/07/fifa-21-PC-sams-store.jpg",
        banner: "https://pickywallpapers.com/img/2020/12/fifa-21-hd-wallpaper-background-2257-2294-hd-wallpapers.jpg",
        description: "FIFA 21 es un videojuego de fútbol del año 2020 disponible para Microsoft Windows, PlayStation 4, Xbox One y Nintendo Switch el 9 de octubre de 2020, y también es el primer videojuego de la serie FIFA para PlayStation 5 y Xbox Series X|S. El juego es la 28.ª entrega de la serie de videojuegos de FIFA.",
        platform: "PlayStation",
        price: 150000,
        video: "https://www.youtube.com/watch?v=tuLAn9adQpI",
        category: "Deportes",
        cantidad: 1,
        __v: 0
    },
    {
        id: 14,
        name: "Crash Bandicoot 4",
        developers: "Toys for Bob",
        image: "https://as.com/meristation/imagenes/2020/06/22/game_cover/503614131592840975.jpg",
        banner: "https://scontent.fbog9-1.fna.fbcdn.net/v/t39.30808-6/241967831_4394315590636109_5329979700751318408_n.jpg?_nc_cat=110&ccb=1-5&_nc_sid=0debeb&_nc_ohc=KlpdozmE2R4AX8eWyJ1&tn=GFcIcWpL9Ezc8Wu8&_nc_ht=scontent.fbog9-1.fna&oh=e27e64678f35af54e1c41f9f91b5b2ce&oe=6143C63F",
        description: "Crash Bandicoot 4: It's About Time es un videojuego de plataformas, diseñado por Toys for Bob y publicado por Activision. El videojuego es la octava entrega de la serie Crash Bandicoot, secuela de Crash Bandicoot N. Sane Trilogy y que toma lugar después de los eventos de Crash Bandicoot 3: Warped.​​​​",
        platform: "PlayStation",
        price: 145000,
        video: "https://www.youtube.com/watch?v=x5K3KaL_xVI",
        category: "Plataformas",
        cantidad: 1,
        __v: 0
    },
    {
        id: 15,
        name: "Call of Duty:Cold War",
        developers: "Activision",
        image: "https://cdn-products.eneba.com/resized-products/PIBTRc3I8RAjBdRDh0kqIHMiapQBb7uy5djFQH-WyB8_350x200_1x-0.jpeg",
        banner: "https://pbs.twimg.com/media/El5w7PkWkAEL0r1.jpg:large",
        description: "Call of Duty: Black Ops Cold War es un videojuego de disparos en primera persona desarrollado por Treyarch y Raven Software y publicado por Activision. Es la quinta entrega Black Ops y el decimoséptimo Call of Duty. Cronológicamente el juego está ambientado después de los acontecimientos de Call of Duty: Black Ops.​",
        platform: "PlayStation",
        price: 85000,
        video: "https://www.youtube.com/watch?v=SvNTIPZTulk",
        category: "Shooter",
        cantidad: 1,
        __v: 0
    },
    {
        id: 16,
        name: "Resident Evil Village",
        developers: "Capcom",
        image: "https://uvejuegos.com/img/caratulas/64645/Resident-Evil-Village-6773-1597925638.jpg",
        banner: "https://scontent.fbog9-1.fna.fbcdn.net/v/t39.30808-6/241820837_4394386703962331_2498896774139130654_n.jpg?_nc_cat=107&ccb=1-5&_nc_sid=0debeb&_nc_ohc=qo1FAFI6udMAX9SHoCf&_nc_ht=scontent.fbog9-1.fna&oh=eba536b0dd7be24dcd8c3b47a6a3d1e4&oe=6143868D",
        description: "Resident Evil Village es un videojuego perteneciente al género de horror de supervivencia desarrollado y publicado por Capcom. la novena entrega de la serie principal de Resident Evil y secuela narrativa .",
        platform: "PlayStation",
        price: 180000,
        video: "https://www.youtube.com/watch?v=ztj8fv6Ttp8",
        category: "Horror de supervivencia",
        cantidad: 1,
        __v: 0
    },
    {
        id: 17,
        name: "Spider-Man: Miles Morales",
        developers: "Insomniac Games",
        image: "https://http2.mlstatic.com/D_NQ_NP_624812-MLV44530771612_012021-O.jpg",
        banner: "https://culturageek.com.ar/wp-content/uploads/2020/11/Culturageek.com_.ar-Spider-man-Miles-Morales-4.jpg",
        description: "Marvel's Spider-Man: Miles Morales es un videojuego de acción y aventuras desarrollado por Insomniac Games y publicado por Sony Interactive Entertainment para PlayStation 4 y PlayStation 5. Está basado en el superhéroe de Marvel Comics Miles Morales.",
        platform: "PlayStation",
        price: 185000,
        video: "https://www.youtube.com/watch?v=Q3kfF3XNzw8",
        category: "Accion y Aventura",
        cantidad: 1,
        __v: 0
    },
    {
        id: 18,
        name : "The Witcher 3: Wild Hunt",
        developers: "CD Projekt RED",
        image: "https://store-images.s-microsoft.com/image/apps.28990.69531514236615003.8f0d03d6-6311-4c21-a151-834503c2901a.d629260e-2bc4-4588-950c-f278cbc22a64",
        banner: "https://scontent.fbog9-1.fna.fbcdn.net/v/t39.30808-6/241962790_4394350710632597_3162139498796545157_n.jpg?_nc_cat=111&ccb=1-5&_nc_sid=0debeb&_nc_ohc=hu9YF9sqNMwAX-tAQZR&_nc_ht=scontent.fbog9-1.fna&oh=e48e9454f119b36b5c075577c1e4e79c&oe=61445465",
        description: "The Witcher 3: Wild Hunt es un videojuego de rol desarrollado y publicado por la compañía polaca CD Projekt RED. Esta compañía es la desarrolladora mientras que la distribución corre a cargo de la Warner Bros. Interactive, en el caso de Norteamérica y Bandai Namco para Europa​",
        platform: "PlayStation",
        price: 50000,
        video: "https://www.youtube.com/watch?v=rXMX4YJ7Lks",
        category: "Accion y Aventura",
        cantidad: 1,
        __v: 0
    },
    {
        id: 19,
        name: "Yakuza: Like a Dragon",
        developers: "Ryu ga Gotoku Studio",
        image: "https://img-grouvee-com.b-cdn.net/upload/cache/2f/23/2f23e6f7c52104b9cb29339eba9a9b26.jpg",
        banner: "https://tecnoticias.net/wp-content/uploads/2021/05/Yakuza-sera-una-serie-de-juegos-de-rol-por-turnos.jpg",
        description: "Yakuza: Like a Dragon, conocido en Japón como Ryū ga Gotoku 7: Hikari to Yami no Yukue, es un videojuego RPG desarrollado y publicado por Sega. Es el octavo juego de la saga principal de Yakuza. Se lanzó en Japón y Asia para PlayStation 4 el 16 de enero de 2020.​",
        platform: "PlayStation",
        price: 180000,
        video: "https://www.youtube.com/watch?v=hkygiqC7ulQ",
        category: "RPG",
        cantidad: 1,
        __v: 0
    },
    {
        id: 20,
        name: "Mortal Kombat 11",
        developers: "NetherRealm Studios, QLOC, Shiver Entertainment",
        image: "https://a.allegroimg.com/s720/116130/3c7622af459f87eb6cf0ca191aa6/MORTAL-KOMBAT-11-STEAM-PC-PL-KLUCZ",
        banner: "https://images4.alphacoders.com/993/thumb-1920-993081.jpg",
        description: "Mortal Kombat 11 es un videojuego de lucha desarrollado por NetherRealm Studios y publicado por Warner Bros. Interactive Entertainment. Se ejecuta en una versión muy modificada de Unreal Engine 3, ​ es la undécima entrega principal de la serie Mortal Kombat y una secuela de 2015 Mortal Kombat X.",
        platform: "PlayStation",
        price: 80000,
        video: "https://www.youtube.com/watch?v=FsfvvYy6oCw",
        category: "Peleas",
        cantidad: 1,
        __v: 0
    }
],
};

export default data;